### ISSUE TITLE
Inputs/Outputs not parsed correctly when defined as a Map

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#211]
if the CWL describes the inputs as a flat map, then the type isn't retrieved and stored during extraction, whereas when described as an Array it is.
e.g from https://github.com/seek4science/seek/blob/master/test/fixtures/files/rp2-to-rp2path.cwl

```
inputs:
  rulesfile: File
  sourcefile: File
  sinkfile: File
  reverse: boolean
  max-steps: int?
```

no, type is extracted, whereas:

```
outputs:
  compounds:
    type: File
    outputSource: rp2paths/compounds
  reactions:
    type: File
    outputSource: rp2paths/reactions
  sinks:
    type: File
    outputSource: rp2paths/sinks
```

works
