### ISSUE TITLE
Publication register button not visible for publications with long metadata

### ISSUE THREAD

**Issue by ChristophB** [seek4science/seek#457]
**Describe the bug**
When fetching publication metadata to register a new publication via DOI (PMID may be affected too), the "Register" button is behind the footer and not visible.

**To Reproduce**
1. Go to '/publications/new#Register'
2. Fill the form with a DOI (e.g. https://doi.org/10.1016/j.cell.2020.09.015)
3. Click on 'Fetch'
4. Scroll down to the end of the page

**Expected behavior**
The page footer should be displayed below the fetched publication metadata.

**Screenshots**
![Bild_2020-11-03_163317](https://user-images.githubusercontent.com/1651973/98006224-46ad8480-1df2-11eb-9ac7-38eb7f55f2f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera (version 71), Chrome (version 86)

**Comment by whomingbird** [comment]
It was a CSS problem.  I have increased the " max-height" for the <div>

**Comment by ChristophB** [comment]
Instead of increasing the max-height, i think it would be more robust to replace
```css
#publication_preview_container {
    max-height: 50em;
}
```
with
```css
#publication_preview_container .panel-body {
    max-height: 26em;
    overflow-y: auto;
}
```
Having a really long title, author list or abstract would otherwise still result into a to large content of the div.
