### ISSUE TITLE
Validation errors should honour the localization name for the model

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#473]
The validation error should use the correct term, rather than the raw model name. For example, when missing to select a Project, but the project has been renamed Team, it should say words to the effect of "Team is required". It currently says Project regardless of the localisation change

**Comment by fbacall** [comment]
https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

**Comment by fbacall** [comment]
We could use YAML anchors for this...

e.g.
```yaml
en:
  investigation: &investigation "Investigation"
  study: &study "Study"
  assay: &assay "Assay"

  activerecord:
    models:
      investigation: *investigation
      study: *study
      assay: *assay
```
